version: "3.3"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: never
    hostname: 'gitlab'
    ports:
      - '8181:80'
      - '4433:443'
      - '2222:22'
    volumes:
      - '${PWD}/gitlab-data/config:/etc/gitlab'
      - '${PWD}/gitlab-data/logs:/var/log/gitlab'
      - '${PWD}/gitlab-data/data:/var/opt/gitlab'

