version: "3.3"
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    hostname: 'gitlab-runner-1'
    container_name: 'gitlab-runner-1'
    volumes:
      - '/var/run/docker.sock:/var/run.docker.sock'
      - '${PWD}/config-runner:/etc/gitlab-runner'
    ports:
      - '8093:8093'
    restart: unless-stopped
